# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='user',
        ),
        migrations.AddField(
            model_name='secret',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_secrets', to='dojo_secrets.User'),
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='liked_secrets', to='dojo_secrets.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
